# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 40

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

  [[main]]
    name = "Test"  # Title of the link.
    url = "landing/"  # Widget Page folder name.
    weight = 70  # Position of the link in the navigation bar.

##    [[main]]
#      name = "About"  # Title of the link.
#      url = "#about"  # Widget Page folder name.
#      weight = 80  # Position of the link in the navigation bar.

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "files/clarke_resume.pdf"
    weight = 80

    [[main]]
      name = "Blog"  # Title of the link.
      url = "landing/"  # Widget Page folder name.
      weight = 90
